####################################################################################################
# Creating container MySQL
####################################################################################################
mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    expose:
        - 3306
    volumes:
        - ./image/mysql/data/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: myapp

####################################################################################################
# Creating container PHP
####################################################################################################
php:
    build: ./image/php/
    ports:
        - "9000:9000"
    volumes:
        - ./www/lumen/:/var/www/html
    links:
        - mysql
    
####################################################################################################
# Creating container (Nginx)
####################################################################################################
nginx:
    image: nginx:latest
    ports:
        - 8080:80
    volumes:
        - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php